apiVersion: batch/v1
kind: Job
metadata:
  name: debugbox-job
spec:
  template:
    spec:
      restartPolicy: Never

      containers:
      - name: debugbox
        image: ghcr.io/ibtisam-iq/debugbox:lite
        imagePullPolicy: Always
        command: ["/bin/bash", "-lc"]
        args:
          - |
            echo "Running DebugBox Job..."
            curl -v https://kubernetes.default.svc
            nslookup google.com
            ip a
            echo "Done."

  backoffLimit: 0
