# Default values for DebugBox Helm chart
replicaCount: 1

image:
  repository: ghcr.io/ibtisam-iq/debugbox
  tag: balanced
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: debugbox-sa

pod:
  privileged: false
  hostNetwork: false
  hostPID: false
  runAsUser: 0
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  tolerations: []
  nodeSelector: {}
  affinity: {}

daemonset:
  enabled: false

rbac:
  create: true
  clusterWide: false

extraVolumes: []
extraVolumeMounts: []

security:
  capabilities:
    add: []
  seccompProfile: runtime/default

env:
  EXTRA_ARGS: ""

deploymentStrategy:
  type: Recreate

# If you want privileged behaviour (e.g., for deep packet capture), set:
# pod.privileged: true
# pod.hostNetwork: true
# rbac.clusterWide: true
