apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debugbox-rolebinding
  namespace: default
  labels:
    app: debugbox
subjects:
  - kind: ServiceAccount
    name: debugbox-sa
    namespace: default
roleRef:
  kind: Role
  name: debugbox-role
  apiGroup: rbac.authorization.k8s.io
