{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: debugbox-rolebinding
  labels:
    app: debugbox
subjects:
  - kind: ServiceAccount
    name: {{ default "debugbox-sa" .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: debugbox-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
